const express = require("express");
const nodemailer = require("nodemailer");
const cors = require("cors");
require("dotenv").config();

const app = express();
app.use(express.json());
app.use(cors()); // Allows your frontend to make requests 

app.use(cors({
  origin: "http://localhost:3000", // Allow requests only from your frontend domain
  methods: ["GET", "POST"],
}));

// POST route to send the form data to the admin email
app.post("/send-email", async (req, res) => {
  const { name, phone, vehicleType, bookingDate } = req.body;

  const transporter = nodemailer.createTransport({
    service: "gmail", // Use Gmail's SMTP service
    auth: {
      user: process.env.emailUser, // Replace with your email
      pass: process.env.emailPass,     // Use an App Password generated by Gmail
    },
  });
  

  const mailOptions = {
    from: process.env.emailUser, // Admin's email
    to:process.env.adminMail, // Admin email where form details will be sent
    subject: "New Vehicle Booking",
    text: `Booking Details:
    Name: ${name}
    Phone: ${phone}
    Vehicle: ${vehicleType}
    Booking Date: ${bookingDate}`,
  };
  // transporter.sendMail(mailOptions, (error, info) => {
  //   if (error) {
  //     console.error("Error sending email:", error);
  //     return res.status(500).json({ error: "Failed to send email", message: error.message });
  //   } else {
  //     console.log("Email sent:", info.response);
  //     return res.status(200).json({ message: "Email sent successfully!" });
  //   }
  // });

  try {
    await transporter.sendMail(mailOptions);
    res.status(200).json({ message: "Email sent successfully!" });
  } catch (error) {
    console.error("Error sending email:", error);
    res.status(500).json({ error: "Failed to send email" });
  }
});

// Start the server
app.listen(5000, () => {
  console.log("Server running on port 5000");
});
