const express = require("express");
const nodemailer = require("nodemailer");
const cors = require("cors");
require("dotenv").config();

const app = express();
app.use(express.json());
app.use(cors()); // Allows your frontend to make requests

// POST route to send the form data to the admin email
app.post("/send-email", async (req, res) => {
  const { name, phone, vehicleType, bookingDate } = req.body;

  const transporter = nodemailer.createTransport({
    service: "gmail", // Use Gmail's SMTP service
    auth: {
      user: process.env.emailUser, // Replace with your email
      pass: process.env.emailPass,     // Use an App Password generated by Gmail
    },
  });

  const mailOptions = {
    from: process.env.emailUser, // Admin's email
    to: "admin-email@example.com", // Admin email where form details will be sent
    subject: "New Vehicle Booking",
    text: `Booking Details:
    Name: ${name}
    Phone: ${phone}
    Vehicle: ${vehicleType}
    Booking Date: ${bookingDate}`,
  };

  try {
    await transporter.sendMail(mailOptions);
    res.status(200).json({ message: "Email sent successfully!" });
  } catch (error) {
    console.error("Error sending email:", error);
    res.status(500).json({ error: "Failed to send email" });
  }
});

// Start the server
app.listen(5000, () => {
  console.log("Server running on port 5000");
});
